package estudo.selenium.pog;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
//Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.interactions.Actions;

public class JorgeematheusTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void jorgeematheus() {
		driver.get("http://192.168.224.93/static/ctmc_agencia_web/#/home");
		driver.manage().window().setSize(new Dimension(1382, 744));
		driver.findElement(By.linkText("* Cadastrar")).click();
		{
			WebElement element = driver.findElement(By.linkText("* Cadastrar"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		driver.findElement(By.cssSelector(".fa-angle-down")).click();
		driver.findElement(By.cssSelector("amb-combobox-item:nth-child(2) > li")).click();
		driver.findElement(By.cssSelector(".fa-sm")).click();
		driver.findElement(By.id("descricao")).click();
		driver.findElement(By.id("descricao")).sendKeys("Jorge e matheus");
		driver.findElement(By.cssSelector("#dataInicio .fa")).click();
		driver.findElement(By.cssSelector("tr:nth-child(5) > .day:nth-child(4)")).click();
		driver.findElement(By.cssSelector("#dataFim .fa")).click();
		driver.findElement(By.cssSelector("tr:nth-child(5) > .day:nth-child(6)")).click();
		driver.findElement(By.cssSelector(".fa-thumbs-o-up")).click();
		driver.findElement(By.cssSelector("#btnConfirmar .btn > span:nth-child(2)")).click();
		driver.findElement(By.cssSelector("#btnOKSucesso .btn > span:nth-child(2)")).click();
		driver.findElement(By.linkText("* Consultar")).click();
		driver.findElement(By.cssSelector(".fa-angle-down")).click();
		driver.findElement(By.cssSelector("amb-combobox-item:nth-child(2) > li")).click();
		driver.findElement(By.cssSelector(".fa-sm")).click();
		driver.findElement(By.id("numeroParametro")).click();
		driver.findElement(By.cssSelector("#dataInicio .fa")).click();
		driver.findElement(By.cssSelector("tr:nth-child(5) > .day:nth-child(4)")).click();
		driver.findElement(By.cssSelector("#dataFim .fa")).click();
		driver.findElement(By.cssSelector("tr:nth-child(5) > .day:nth-child(6)")).click();
		driver.findElement(By.cssSelector(".fa-sm")).click();
		driver.findElement(By.cssSelector(".amb-row:nth-child(2) > .cdk-column-parametro")).click();
		driver.findElement(By.cssSelector(".amb-row:nth-child(3) > .cdk-column-parametro")).click();
		driver.findElement(By.cssSelector(".col-sm-1:nth-child(3)")).click();
		driver.findElement(By.cssSelector(".col-sm-1:nth-child(3)")).click();
		driver.findElement(By.cssSelector(".fa-newspaper-o")).click();
		driver.findElement(By.cssSelector(".modal-dialog-manual span")).click();
		driver.findElement(By.cssSelector(".hicon-118")).click();
	}
}
